### ISSUE TITLE
The built keys have changed in trilingual courses

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus-rst-tools#126]
After #125, https://github.com/apluslms/mooc-grader/issues/96 and #118, there is a bug left. In the trilingual test-course (https://github.com/apluslms/test-course/tree/trilingual), there are changes in the built keys. The keys should not change due to the bug fixes because new keys could cause severe issues in existing courses.

Using a-plus-rst-tools master branch, in test-course trilingual branch, after a clean build, in `_build/yaml/index.yaml`, I see that the first exercise in the links1/chapter1 has key `links1_chapter1_p` and `config: links1_chapter1_p.yaml`. The key before the bug fix did not include `_p`.

Changing keys could cause problems in production due to how A+ (aplus-json) course import uses keys. It could create new empty exercises with new keys and hide old submissions in the old exercises because the new keys do not match the exercise keys in the A+ database that were created before upgrading a-plus-rst-tools.

**Comment by skulonen** [comment]
@Mankro I tested this with the test-course trilingual branch. I first ran docker-compile using the latest version of aplus-rst-tools. Then I checked out the commit **before** my latest fix and ran docker-compile again. The contents of index.yaml are identical between the two cases. The key is `links1_chapter1_p` in both files and the value of config is `links1_chapter1_p.yaml` in both files.

Did I misunderstand the problem here?

**Comment by Mankro** [comment]
Right, trilingual courses have always been broken and we have not yet used them in production. However, bilingual courses would not have the strange `_p` ending in the key. If a bilingual course in converted to a trilingual course, then we would really have issues with the changing key. Ideally, these keys must be the same in bilingual and trilingual courses that have identical structure.

**Comment by skulonen** [comment]
I see, good point. I had previously fixed the key generation issue in #125, but then reverted it because we got the idea that we shouldn't change the key generation logic to avoid changing existing keys. But seeing as trilingual courses have not been used in production, and bilingual courses never had the issue with key generation, it seems like we should use the fix after all.

I'll check that the fix doesn't cause changes in keys or filenames in a bilingual course, and that the keys remain the same after converting it to a trilingual course.
